[package]
version = "0.1.0"
name = "receipts-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "2.0.0"
receipts-lib = { path = "../lib" }
serde = { version = "1.0.106", default-features = false, features = ["derive"] }
serde_cbor = "0.11.2"